# Generated by Django 2.1.7 on 2019-04-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to=settings.AUTH_USER_MODEL),
        ),
    ]
