# Generated by Django 2.1.7 on 2019-04-20 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190419_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='dashboard.Machines'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machines',
            name='owner',
            field=models.ManyToManyField(related_name='machine', to=settings.AUTH_USER_MODEL),
        ),
    ]
