# Generated by Django 2.1.7 on 2019-04-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190420_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicillum', models.IntegerField()),
                ('minutsbomba', models.IntegerField()),
                ('horarefill', models.IntegerField()),
                ('horesllum', models.IntegerField()),
                ('tempmax', models.IntegerField()),
                ('tempmin', models.IntegerField()),
                ('phmax', models.IntegerField()),
                ('phmin', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines2', to='dashboard.Machines')),
            ],
        ),
    ]
