# Generated by Django 2.1.7 on 2019-04-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llum', models.BooleanField()),
                ('bomba_aigua', models.BooleanField()),
                ('bomba_nutri1', models.BooleanField()),
                ('bomba_nutri2', models.BooleanField()),
                ('bomba_oxigen', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines3', to='dashboard.Machines')),
            ],
        ),
    ]
