# Generated by Django 2.1.7 on 2019-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_machinestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestate',
            name='ventilador',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
